/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lichao_javafilecrpt_Cryptor */

#ifndef _Included_com_lichao_javafilecrpt_Cryptor
#define _Included_com_lichao_javafilecrpt_Cryptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lichao_javafilecrpt_Cryptor
 * Method:    crypt
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_lichao_javafilecrpt_Cryptor_crypt
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_lichao_javafilecrpt_Cryptor
 * Method:    drypt
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_lichao_javafilecrpt_Cryptor_drypt
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
